/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        FlipCoin flipCoin = new FlipCoin();
        flipCoin.flipCoin(0, 10, 10);
        flipCoin.flipCoin(25, 100, 10);
        flipCoin.flipCoin(50, 250, 10);
        flipCoin.flipCoin(75, 500, 10);
        flipCoin.flipCoin(100, 1000, 10);


    }
}
